<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AI_driven_OSINT_platform</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="obj\**" />
    <Content Remove="obj\**" />
    <EmbeddedResource Remove="obj\**" />
    <None Remove="obj\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Backend\Core\Configurations\" />
    <Folder Include="Backend\Core\DbContexts\" />
    <Folder Include="Backend\Core\Security\" />
    <Folder Include="Backend\Features\BaseFeature\Controllers\" />
    <Folder Include="Backend\Features\BaseFeature\Models\" />
    <Folder Include="Backend\Features\BaseFeature\Data\" />
    <Folder Include="Backend\Features\BaseFeature\Infrastruture\" />
    <Folder Include="Backend\Features\BaseFeature\Services\" />
    <Folder Include="Backend\Middleware\" />
    <Folder Include="Backend\Shared\Kernel\" />
    <Folder Include="Backend\Shared\Logging\" />
    <Folder Include="Backend\Shared\Helpers\" />
    <Folder Include="Backend\Shared\Services\" />
    <Folder Include="Backend\Shared\Utilities\" />
    <Folder Include="Documentation\API Docs\GraphQL\" />
    <Folder Include="Documentation\API Docs\Swagger\" />
    <Folder Include="Frontend\Public\" />
    <Folder Include="Frontend\Src\Contexts\" />
    <Folder Include="Frontend\Src\Services\" />
    <Folder Include="Frontend\Src\Shared\hooks\" />
    <Folder Include="Frontend\Src\Shared\components\" />
    <Folder Include="Frontend\Src\Shared\utils\" />
    <Folder Include="Frontend\Src\Styles\" />
    <Folder Include="Frontend\Src\Utils\" />
    <Folder Include="Frontend\Tests\Integration\" />
    <Folder Include="Frontend\Tests\Unit\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.24" />
  </ItemGroup>

</Project>
